### ISSUE TITLE
"Error: Cannot find module 'lodash/core'\nRequire stack:\n- /var/task/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"

### ISSUE THREAD

**Issue by ghost** [starschema/starsnow_request#4]
This is the error I get when calling the function inside snowflake: 
`Request failed for external function STARSNOW_REQUEST_GET with remote service error: 502 '{"message": "Internal server error"}'; requests batch-id: 01a06e8d-0500-ddbd-000c-34030134c776:0:0; request batch size: 1 rows; request retries: 9; response time (last retry): 266.04ms`

On the AWS logs, this is what I see. 
```
2021-11-21T05:07:07.762Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'lodash/core'\nRequire stack:\n- /var/task/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lodash/core'",
        "Require stack:",
        "- /var/task/handler.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by ghost** [comment]
This is what the zip file in s3 looks like. I downloaded opened it up. 
![image](https://user-images.githubusercontent.com/89102347/142766231-beb4a29e-e83d-4d32-9b7b-6ecec1ca59f8.png)

**Comment by tfoldi** [comment]
Can you retry with the latest version (the latest version uses serverless plugin 0.1.5)? 

What is your serverless framework core version?

**Comment by tfoldi** [comment]
seems `npm install` was missing before `sls deploy`.
